**1. Write a Pandas program to create and display a 1-D array like object containing an array of data using Pandas module.**

In [ ]:
import pandas as pd
import numpy as np
ds = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(ds)
print(ds*ds)
print(ds**ds)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64
0              1
1              4
2             27
3            256
4           3125
5          46656
6         823543
7       16777216
8      387420489
9    10000000000
dtype: int64


**2. Write a Pandas program to convert a Pandas module Series into a Python list.**

In [ ]:
import pandas as pd
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


**3. Write a Pandas pragram to add, subtract, multiply and divide two Pandas Series.**

In [ ]:
import pandas as pd
import numpy as np
ds1 = pd.Series([2,4,6,8,10])
ds2 = pd.Series([1,3,5,7,9])
print("Addition of the series is :","\n",ds1+ds2)
print("Subtraction of the series is :","\n",ds1-ds2)
print("Multiplication of the series is :","\n",ds1*ds2)
print("Division of the series is :","\n",ds1/ds2)

Addition of the series is : 
 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction of the series is : 
 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication of the series is : 
 0     2
1    12
2    30
3    56
4    90
dtype: int64
Division of the series is : 
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


**4. Write a Pandas program to compare the elements of the two Pandas series.**

In [ ]:
import pandas as pd
ds1 = pd.Series([2,4,6,8,10])
ds2 = pd.Series([1,3,5,7,10])
print("Series 1 :",ds1)
print("Series 2 :",ds2)
print("Comparing ds1 less than ds2 :","\n",ds1<ds2)
print("Comparing ds1 greater than ds2 :","\n",ds1>ds2)
print("Comparing ds1 equal to ds2 :","\n",ds1==ds2)

Series 1 : 0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2 : 0     1
1     3
2     5
3     7
4    10
dtype: int64
Comparing ds1 less than ds2 : 
 0    False
1    False
2    False
3    False
4    False
dtype: bool
Comparing ds1 greater than ds2 : 
 0     True
1     True
2     True
3     True
4    False
dtype: bool
Comparing ds1 equal to ds2 : 
 0    False
1    False
2    False
3    False
4     True
dtype: bool


**5. Write a Pandas program to convert a dictionary to a Pandas series.   
Sample Series:    
Original dictionary : {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}**

In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
print("Original Dictionary :")
print(d1)
n_series = pd.Series(d1)
print("Converted Series : ")
print(n_series)

Original Dictionary :
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted Series : 
a    100
b    200
c    300
d    400
e    800
dtype: int64


**6.  Write a Pandas program to convert a numpy array to a Pandas series.**

In [ ]:
import pandas as pd
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("NumPy Array :","\n",arr1)
new_s = pd.Series(arr1)
print("Converted series :","\n",new_s)

NumPy Array : 
 [ 1  2  3  4  5  6  7  8  9 10]
Converted series : 
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


**7. Write a Pandas program to change the datatype of a given column or a series.**

In [ ]:
import pandas as pd
s1 = pd.Series(['18','100','200','pyhton','harshit','300.12','69.69'])
print("original Series :","\n",s1)
ns = pd.to_numeric(s1, errors = 'coerce')
print("Converted Series :","\n",ns)

original Series : 
 0         18
1        100
2        200
3     pyhton
4    harshit
5     300.12
6      69.69
dtype: object
Converted Series : 
 0     18.00
1    100.00
2    200.00
3       NaN
4       NaN
5    300.12
6     69.69
dtype: float64


**8. Write a Pandas program to convert a series into an array.**

In [ ]:
import pandas as pd
import numpy as np
new_s = pd.Series([1,2,3,4,5,6,7,8,9,10])
print("Original series :","\n",new_s)
arr1 = np.array(new_s)
print("Converted from series to numpy array :",'\n',arr1)
s1 = new_s.values
print("Converted from series to array :","\n",s1)
print(type(s1))

Original series : 
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
Converted from series to numpy array : 
 [ 1  2  3  4  5  6  7  8  9 10]
Converted from series to array : 
 [ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


**9. Write a Pandas program to convert Series of lists to one series.   
Sample Output :      
Original Series of list   
0    [Red, Green, White]     
1            [Red,Black]     
2               [Yellow]**

In [ ]:
import pandas as pd
s1 = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red','Black'],
    ['Yellow']])
print("Original Series of list :","\n",s1)
s1 = s1.apply(pd.Series).stack().reset_index(drop = True)
print("One Series","\n",s1)

Original Series of list : 
 0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series 
 0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


**10. Sort the list.**

In [ ]:
import pandas as pd
s1 = pd.Series(['18','100','200','pyhton','harshit','300.12','69.69'])
print("original Series :","\n",s1)
new_s = pd.Series(s1).sort_values()
print("New Series :","\n",new_s)

original Series : 
 0         18
1        100
2        200
3     pyhton
4    harshit
5     300.12
6      69.69
dtype: object
New Series : 
 1        100
0         18
2        200
5     300.12
6      69.69
4    harshit
3     pyhton
dtype: object


**11. In this series '18','100','200','pyhton','harshit','300.12','69.69'add 500 and php**

In [ ]:
import pandas as pd
s1 = pd.Series(['18','100','200','pyhton','harshit','300.12','69.69'])
print("original Series :","\n",s1)
print("\n Data Series after adding some data :")
new_s = pd.concat([s1, pd.Series([10, "Messi"])],ignore_index = True) # ignore index is for new index for new series.
print(new_s)

original Series : 
 0         18
1        100
2        200
3     pyhton
4    harshit
5     300.12
6      69.69
dtype: object

 Data Series after adding some data :
0         18
1        100
2        200
3     pyhton
4    harshit
5     300.12
6      69.69
7         10
8      Messi
dtype: object


**12. Write a Pandas program to change the order in index of a given series.**

In [ ]:
import pandas as pd
s1 = pd.Series(data = [1,2,3,4,5], index = ['A','B','C','D','E'])
print("Original Data Series :","/n",s1)
s1 = s1.reindex(index = ['C','B','A','E','D'])
print("Converted series :","\n",s1)

Original Data Series : /n A    1
B    2
C    3
D    4
E    5
dtype: int64
Converted series : 
 C    3
B    2
A    1
E    5
D    4
dtype: int64


**13. Write a Pandas program to get the items of a given series not present into another given series.**

In [ ]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([2,4,8,10])
print("Series 1 :","\n",s1)
print("Series 2 :","\n",s2)
not_ins1 = s1[~s1.isin(s2)]
print("Elements that are not present in series 2 :","\n",not_ins1)

Series 1 : 
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series 2 : 
 0     2
1     4
2     8
3    10
dtype: int64
Elements that are not present in series 2 : 
 0    1
2    3
4    5
dtype: int64
