# **Chapter 4. Handling numerical data**
Overflowing entering more higher value than expected. eg:- entering 16 digit value in 15 digit model.

Underflowing entering more lower value than expected. eg:- entering 16 digit value in 15 digit model.

**Scalers**    
***StandardScaler*** : Standardize features by removing the mean and scaling to unit variance.       
 It is effected by outliers.   
Outliers are the wrong values in the the data.  
Formula : z = (x - u) / s  

***MinMaxScaler*** : It will consider most repeating value as the maximum value. It is not effected by outliers. It neglects the outliers.

***MaxAbsScaler*** : it will give positive values as output. It there is any negative values in the datasets use this function.

***RobustScaler*** : it only work from 25 quatile to 75 quatile i.e. 25% to 75%. It will neglect the outlier as outliers are either the lower than 25 quatile or higher than 75 quatile.


**MinMaxScaler**

In [ ]:
import numpy as np
from sklearn import preprocessing
feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

# Create a scaler
minmax_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))

# Scale feature
scaled_feature = minmax_scaler.fit_transform(feature)

print("MinMaxScaler : \n",scaled_feature)

MinMaxScaler : 
 [[0.        ]
 [0.28571429]
 [0.35714286]
 [0.42857143]
 [1.        ]]


**StanderdScaler**

In [ ]:
import numpy as np
from sklearn import preprocessing
features1 = np.array([[-1000.1],
                      [-200.2],
                      [500.5],
                      [600.6],
                      [9000.9]])

# Create a scaler
std_scaler = preprocessing.StandardScaler()

# Scale feature
scaled_feature1 = std_scaler.fit_transform(features1)

print("StandardScaler : \n",scaled_feature1)

print("Mean : {}".format(round(scaled_feature1.mean())))
print("Standard Deviation : {}".format(round(scaled_feature1.std())))

StandardScaler : 
 [[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Mean : 0
Standard Deviation : 1


**RobustScaler**

In [ ]:
import numpy as np
from sklearn import preprocessing
features2 = np.array([[-1000.1],
                      [-200.2],
                      [500.5],
                      [600.6],
                      [9000.9]])

# Create a scaler
robust_scaler = preprocessing.RobustScaler()

# Scale feature
scaled_feature2 = robust_scaler.fit_transform(features2)

print("RobustScaler : \n",scaled_feature2)

RobustScaler : 
 [[-1.87387612]
 [-0.875     ]
 [ 0.        ]
 [ 0.125     ]
 [10.61488511]]


**Normalizatin**

In [ ]:
import numpy as np
from sklearn.preprocessing import Normalizer
feature = np.array([[0.5,0.5],
                    [1.1,3.4],
                    [1.5,20.2],
                    [1.63,34.4],
                    [10.9,3.3]])

#create normalizer
normalizerl1 = Normalizer(norm = "l1")
normalizerl2 = Normalizer(norm = "l2")
normalizermax = Normalizer(norm = "max")

#tranform feature matrix
print("l1 normalization : \n",normalizerl1.transform(feature))
print("\n l2 normalization : \n",normalizerl2.transform(feature))
print("\n max normalization : \n",normalizermax.transform(feature))

l1 normalization : 
 [[0.5        0.5       ]
 [0.24444444 0.75555556]
 [0.06912442 0.93087558]
 [0.04524008 0.95475992]
 [0.76760563 0.23239437]]

 l2 normalization : 
 [[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]

 max normalization : 
 [[1.         1.        ]
 [0.32352941 1.        ]
 [0.07425743 1.        ]
 [0.04738372 1.        ]
 [1.         0.30275229]]


**Grouping the observation.**

In [ ]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
features,_ = make_blobs (n_samples = 50,
                        n_features = 2,
                        centers = 3 ,
                        random_state= 1)
df = pd.DataFrame(features, columns= ["feature_1", "feature_2"])
clusterer = KMeans (3, random_state=0)
clusterer.fit(features)
df['group'] = clusterer.predict(features)
df.head()

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

**Deleting observation with missing values.**

In [ ]:
import numpy as np
features = np.array([[1.1,11.1],
             [2.2,22.2],
             [3.3,33.3],
             [np.nan,55]])

features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3]])

**Imputing missing values.**   
There are two types of imputing.
1. Univarient - Single value to change. It uses Simple Imputation.
2. Multivarient - More than one value to change. It uses iterative Imputation.


1. Mean

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
features = np.array([[1.1,11.1],
             [2.2,22.2],
             [3.3,33.3],
             [np.nan,55]])
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(features)
SimpleImputer()
print(imp_mean.transform(features))

[[ 1.1 11.1]
 [ 2.2 22.2]
 [ 3.3 33.3]
 [ 2.2 55. ]]


2. Median

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
features = np.array([[1.1,11.1],
             [2.2,22.2],
             [3.3,33.3],
             [np.nan,55]])
imp_mean = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean.fit(features)
SimpleImputer()
print(imp_mean.transform(features))

[[ 1.1 11.1]
 [ 2.2 22.2]
 [ 3.3 33.3]
 [ 2.2 55. ]]


3. Most frequent

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
features = np.array([[1.1,11.1],
             [2.2,22.2],
             [3.3,33.3],
             [np.nan,55]])
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp_mean.fit(features)
SimpleImputer()
print(imp_mean.transform(features))

[[ 1.1 11.1]
 [ 2.2 22.2]
 [ 3.3 33.3]
 [ 1.1 55. ]]


4. Constant

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
features = np.array([[1.1,11.1],
             [2.2,22.2],
             [3.3,33.3],
             [np.nan,55]])
imp_mean = SimpleImputer(missing_values=np.nan, strategy='constant')
imp_mean.fit(features)
SimpleImputer()
print(imp_mean.transform(features))

[[ 1.1 11.1]
 [ 2.2 22.2]
 [ 3.3 33.3]
 [ 0.  55. ]]
