**Numpy Datatypes**
1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type (void)

**Example 1:**

In [ ]:
import numpy as np
arr = np.array([1.1,2.2,3.3,4.4,5.5]) #Float datatype
print(arr.dtype)

float64


**Example 2:**

In [ ]:
import numpy as np
arr = np.array(['Harshit','Manan','Ankit','Saksham','Raj'])
print(arr.dtype)

<U7


**Example 3:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5], dtype = 'S') # S is the for string data type.
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


**Example 4:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5], dtype = 'i4') # i is for interger datatype with 4 for 4 byte.
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


**Example 5:**

In [ ]:
import numpy as np
arr = np.array(['a','2','3'], dtype = 'i') # i is for interger; a is a string.
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

**Converting Datatype on existing array.**

In [ ]:
import numpy as np
arr = np.array([1.1,2.1,3.1]) # float
newarr = arr.astype('int') # astype is used to change the datatype. If we use 'i' it wil show 32 byte and if we use 'int' it will show 64 byte.
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


**Example 1:**

In [ ]:
import numpy as np
arr = np.array([1,0,4,0.5,-1]) # Except 0 every number is true.
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True  True]
bool


**Example 2:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


**Copy in Numpy**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy() # only changes the 1st array
arr[0]= 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**View in Numpy**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view() #changes both array
arr[0]= 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0]= 410
print(arr)
print(x)

[410   2   3   4   5]
[410   2   3   4   5]


**Check if array owns its data**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


**Q1. Create an array with 5 student name, create a view with the reference to student array.        
a. Copy the student array into array_library.     
b. Print name of student 2.       
c. Print name of student 4.   
d. Print name last student.    
e. Change the name of 3rd student to 'Jay' using view.**

In [ ]:
import numpy as np
std_array = np.array(['Harshit','Raj','Ankit','Manan','Saksham']) # Main array
v_std = std_array.view() # View array
array_library = std_array.copy() # Copy array
print('a.',array_library)
print('b. Print name of student 2 :',std_array[1])
print('c. Print name of student 4 :',std_array[3])
print('d. Print name of last student :',std_array[-1])
v_std[2] = 'Jay' # Name changed
print('e.',v_std)
print('Main array after making changes in view array :',std_array) # changes in view array also changes the main array.

a. ['Harshit' 'Raj' 'Ankit' 'Manan' 'Saksham']
b. Print name of student 2 : Raj
c. Print name of student 4 : Manan
d. Print name of last student : Saksham
e. ['Harshit' 'Raj' 'Jay' 'Manan' 'Saksham']
Main array after making changes in view array : ['Harshit' 'Raj' 'Jay' 'Manan' 'Saksham']


**Numpy array shape.**     
Shape of an array.

**Example 1:**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2 rows, 5 column.
print(arr.shape)

(2, 5)


**Example 2:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print('Shape of the array :',arr.shape)

[[[[[1 2 3 4 5]]]]]
Shape of the array : (1, 1, 1, 1, 5)


**Convertion of dimension of an array**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Example 1:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Example 2:**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
v_arr = arr.view()
c_arr = arr.copy()
nv_arr = v_arr.reshape(2,3)
nc_arr = c_arr.reshape(2,3)
print('Reshaped view array :',nv_arr)
print('Main array :',arr)
print('Reshaped copy array :',nc_arr)
print(arr.reshape(2,3).base)
print(v_arr.reshape(2,3).base)
print(c_arr.reshape(2,3).base)

Reshaped view array : [[1 2 3]
 [4 5 6]]
Main array : [1 2 3 4 5 6]
Reshaped copy array : [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


**Example 3:**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
n_arr = arr.reshape(-1)
print(n_arr)

[1 2 3 4 5 6]
