# **Numpy Array Iterating**    
**Iterating Array**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


**Iterating 2-D Arrays**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


**Iterating 3-D Arrays**

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


**Iterating Arrays Using nditer()**

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Iterating Array With Different Data Types**

In [ ]:
import numpy as np
arr = np.array([1,2,3])
for x in np.nditer(arr, flags = ['buffered'],op_dtypes = ['S']):
  print(x)


b'1'
b'2'
b'3'


**Iterating With Different Step Size**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::3]):
  print(x)

1
4
5
8


**Enumerated Iteration Using ndenumerate()**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


**1. Create one 2D array with the number 1,2,3,4,5 in the 1st and 6,7,8,9,10 in the 2nd array. Find multiple of 2 of all the element present in your 2D array.**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(arr[0]):
  print(x*2)

2
4
6
8
10


**2.**

In [ ]:
import numpy as np
arr = np.array([[80,70],
                [50,20],
                [60,30],
                [90,40]
                ])
print(sum(arr[:,0]))
print(sum(arr[:,1]))

TypeError: 'numpy.ndarray' object is not callable