**To Install numpy.**

In [ ]:
pip install nump

**Import numpy**

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**Example**

In [ ]:
import numpy as np
ar = np.array([2,4,6,8,1])
print(ar)

[2 4 6 8 1]


**Checking numpy version**

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


**To check datatype of your array**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


**1D array**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(ar)

[2 4 6 8 1]


**OD Array**

In [ ]:
import numpy as np
arr = np.array(22)
print(arr)

22


**2D Array**

In [ ]:
import numpy as np
arr = np.array([[2,4,6],[1,3,5]])
print(arr)

[[2 4 6]
 [1 3 5]]


**3D array**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Check dimension of array**

In [ ]:
import numpy as np
a = np.array(22)
b = np.array([1,2,3,4,5])
c = np.array([[2,4,6],[1,3,5]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Create an array with 5 dimension and verify that it has 5 dimension**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('Number of the dimension : ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of the dimension :  5


# **Numpy Array Indexing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0]) #indexing starts with 0

1


**Adding two number of the array using indexing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0]+arr[2])

4


**Class Work**

In [ ]:
import numpy as py
arr1 = np.array([11,12,13,14,15])
arr3 = np.array([16,17,18,19,20])
#Print 2nd element of arr1
print('Print 2nd element of arr1 : ',arr1[2])
#Print 19 from arr3
print('Print 19 from arr3 : ',arr3[3])
#Add 3rd element of arr1 and 5th element of arr3
print('Add 3rd element of arr1 and 5th element of arr3 : ',arr1[2] + arr3[4])
#Sum of arr1
print('Sum of arr1 : ',sum(arr1))
#Sum of arr3
print('Sum of arr3 : ',sum(arr3))
#Find the total of arr1 and arr3
print('Find the total of arr1 and arr3 : ',sum(arr1) + sum(arr3))

Print 2nd element of arr1 :  13
Print 19 from arr3 :  19
Add 3rd element of arr1 and 5th element of arr3 :  33
Sum of arr1 :  65
Sum of arr3 :  90
Find the total of arr1 and arr3 :  155


**Create a 2D array and print 2nd element od 2nd array.**

In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Print 2nd element od 2nd array :',arr[1,1])

Print 2nd element od 2nd array : 7


**Create a 3D array and print 2nd array of 1st array.**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1])

[4 5 6]


**Negative Indexing.**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[-1,-1,-3])#Negative indexing starts from last element

10


## **Numpy Array slicing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:4])#print 2 3 4

[1 2 3 4 5 6 7]
[2 3 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:])#print using

[1 2 3 4 5 6 7]
[2 3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[:4])

[1 2 3 4 5 6 7]
[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[:-4])

[1 2 3 4 5 6 7]
[1 2 3]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:5:3])#last argument is for skipping elements

[1 2 3 4 5 6 7]
[2 5]


**Slice element from index 1 to index 4 from 2nd element(Sub array)**

In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:3])

[2 3]


In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])#1st argument is from inclusive of both element and second argument is for the indexing

[4 9]


In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as py
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:3,2:5])

[[ 3  4  5]
 [ 8  9 10]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::3])

[1 4 7]
